### ISSUE TITLE
Verse Missing 

### ISSUE THREAD

**Issue by LiziRaju** [friendsofagape/autographa-lite#157]
The MTTs were facing the issue of verses getting jumbles and few verses missing, but the same USFM file inside paratext shows correct
[fwd.zip](https://github.com/friendsofagape/autographa-lite/files/4069867/fwd.zip)
 verses. Issues is only in autographa.

**Comment by LiziRaju** [comment]
It is fixed.

**Comment by Ashersam** [comment]
Closed. Since we could not recreate the issue. works well and tested.
