### ISSUE TITLE
Confusing icon

### ISSUE THREAD

**Issue by RobH123** [friendsofagape/autographa-lite#50]
In v1.2.1 on Ubuntu, scrolling over icon of quill on scroll (top left of main window) changes the pointer to a hand (implying a clickable link), but clicking seems to have no effect.

**Comment by joelthe1** [comment]
Thanks for pointing this out. We'll add this to our next release which should be soon.

**Comment by joelthe1** [comment]
The issue is fixed in v1.2.2. Thanks again!
