### ISSUE TITLE
Translation column length

### ISSUE THREAD

**Issue by Yulni** [friendsofagape/autographa-lite#66]
Hello, I have a strange problem with the v1.2.3 release. The language that I am working in requires at least 15 to 20% more space than the English texts. When I am typing or copying and pasting in verses of translated text the program will allow me to scroll down to the third to last or second to last verse in either a full screen window mode or a half screen window, either 2 or 3 column view. The last verse I cannot get to, neither by down arrow, PgDn or scrolling functions with mouse. The ONLY  way I can get to the last verse in a chapter is to narrow the screen until the columns are barely a one inch or two wide, basically a couple of words wide, and then the last verse will show up. It is mildly annoying to work with...

Benjamin Sullivan [10:33]
Another thought...
If the columns were individually adjustable for width on the Source Text then this column(s) could be narrowed with respect to the Translation column thereby creating sufficient length in the translation column and making accessible all verses in each chapter.

**Comment by joelthe1** [comment]
Benjamin SullivanI was able recently to complete loading of the Autograph Lite program with the 1865 Reina Valera Spanish Bible as a Reference/Source text in a computer going to the team in Nicaragua. After loading the Translation, Mayangna texts I tested the view of the windows in several chapters. It was disappointing to find that the greater volume of text i.e. Mayangna has more syllables per word on average than Spanish or English, caused the last verse or two of the Translation window to be invisible. It was almost impossible to see the last verse or two even when I narrowed the program window down to a minimum width and displayed only one or two words per column. Needless to say I am very much looking forward to individually adjustable column width if that is in your development agenda.
