### ISSUE TITLE
Book and Chapter names

### ISSUE THREAD

**Issue by mondele** [friendsofagape/autographa-lite#87]
Currently Autographa doesn't support entering book and chapter names localized for the target language.

**Comment by joelthe1** [comment]
Thanks for bringing this up. Not the first time though. We are working to improve the editing experience in Autographa Lite to the point that these features would be covered. Stay tuned.

**Comment by joelthe1** [comment]
The book name part of this issue has been addressed via a new feature that was added and made available in [this](https://github.com/friendsofagape/autographa-lite/releases/tag/1.3.5-beta.1) release.

**Comment by joelthe1** [comment]
There isn't more information given regarding what translation of `chapter names` means, so closing this issue for now.
